/**
 * User Service REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponse } from './userResponse';


export interface PingResponse { 
    text?: string;
    user?: UserResponse;
    timestamp?: string;
}

