/**
 * Car Logbook Service REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const Gasoline = {
    Gasoline: 'GASOLINE',
    Diesel: 'DIESEL',
    Hybrid: 'HYBRID',
    Electric: 'ELECTRIC'
} as const;
export type Gasoline = typeof Gasoline[keyof typeof Gasoline];

