/**
 * Car Logbook Service REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ImportType = {
    Vehicle: 'VEHICLE',
    LogbookEntry: 'LOGBOOK_ENTRY',
    LogbookFuelEntry: 'LOGBOOK_FUEL_ENTRY'
} as const;
export type ImportType = typeof ImportType[keyof typeof ImportType];

