/**
 * Car Logbook Service REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sortDirection';
import { LogbookFuelEntry } from './logbookFuelEntry';


export interface LogbookFuelEntryResultList { 
    entries?: Array<LogbookFuelEntry>;
    results?: number;
    sort?: string;
    direction?: SortDirection;
}
export namespace LogbookFuelEntryResultList {
}


