/**
 * Car Logbook Service REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDirection } from './sortDirection';
import { LogbookEntry } from './logbookEntry';


export interface LogbookEntryResultList { 
    entries?: Array<LogbookEntry>;
    results?: number;
    sort?: string;
    direction?: SortDirection;
}
export namespace LogbookEntryResultList {
}


