/**
 * Car Logbook Service REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PingResponse { 
    text?: string;
    username?: string;
    /**
     * ID
     */
    uid?: string;
    timestamp?: string;
}

