export * from './forgot.service';
import { ForgotService } from './forgot.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './me.service';
import { MeService } from './me.service';
export * from './ping.service';
import { PingService } from './ping.service';
export * from './refresh.service';
import { RefreshService } from './refresh.service';
export * from './register.service';
import { RegisterService } from './register.service';
export * from './reset.service';
import { ResetService } from './reset.service';
export const APIS = [ForgotService, LoginService, MeService, PingService, RefreshService, RegisterService, ResetService];
